# goal definition
# whether or not initial contact is done
bool is_on_contact
# timeout to finish the action [s]
int32 timeout
# minimum force expected per entry
float32 th_min_force
# wether we learn the devaition before the contact
bool is_std_learned
---
# result definition
# action success
bool success
# wether stopped on time_out
bool is_timeout
# maximum deformation force (N)
float32 max_force_deformation
# maximum snap force (N)
float32 max_force_snap
---
# feedback definition
# current status
int32 current_stage
# current maximum deformation force (N)
float32 max_force_deformation
# current maximum snap force (N)
float32 max_force_snap
