#!/usr/bin/env python
"""
@package ibd_test_data
@file wrench_from_csv
@author Anthony Remazeilles
@brief Package containing reference data for initial dev
        Entry point to the node.
Copyright (C) {packageCopyright}
https://www.gnu.org/licenses/gpl.txt
"""
from ibd_test_data.wrench_from_csv_ros import main

if __name__ == '__main__':
    main()
